Feat/preview modal
nerdbord/joboard-app-lm3oi79m pull request #21
Opened 2023-11-01 19:57 UTC by blocdenis

2023-11-02 17:19 UTC, Sumick requested changes
Mostly looks good, but we need to clean up this PR before merging. Only preview modal  related changes should be present here

2023-11-02 17:19 UTC, Sumick commented on package.json
> +      "npm": "^10.2.1",
**nitpick:** This 2 should be removed

2023-11-02 17:19 UTC, Sumick commented on src/components/Checkbox/Checkbox.test.tsx
> +
**nitpick:** tests should not be a part of this PR

2023-11-02 17:19 UTC, Sumick commented on src/components/Checkbox/Checkbox.tsx
> +//    const handleClick = (event: React.MouseEvent<HTMLInputElement>) => {
**nitpick:** Im not sure it should be commented out

2023-11-02 17:19 UTC, Sumick commented on src/components/Modal/OfferDetailsModal.tsx
> +      const createdAtDate = new Date(createdAt);
**nitpick:** This should be a utility function, that is imported here. You would easily reuse such function in other places in the system

2023-11-02 17:19 UTC, Sumick commented on src/components/Modal/OfferDetailsModal.tsx
> +                           alt="image of offer"
**nitpick:** It would be good to add company title as `alt` instead of hardcoded value

2023-11-02 17:19 UTC, Sumick commented on src/components/OffersList/OffersList.tsx
> +      useContext(DataContext);
**nitpick:** I would split contexts as its currently one big DataContext - it's not too meaningful. You could do `ModalContext`, and `JobOffersContext` for example

2023-11-03 19:19 UTC, NerdbordMentor approved these changes
## Code Review Report

### Task goal
We should be able to preview job offer in its modal

### Requirements
- UI should be implemented based on [design](https://www.figma.com/file/2f23T1l0pY13cBgsEyL5es/Nerdbord-x-Joboard?node-id=31-0&amp;t=HXGyDxdzTDuSZZLS-4)
- `Visit offer` button should redirect to the employer offer URL

### Review

The code changes seem to cover the task requirements. The UI has been updated according to the design and the `Visit offer` button redirects to the employer offer URL.

#### src/components/Modal/OfferDetailsModal.tsx
The modal component has been updated to display the job offer details. The `Visit offer` button has been implemented and it redirects to the employer offer URL as required. The UI changes match the design provided.

#### src/components/Offer/Offer.tsx
The Offer component has been updated to include an image and a click handler that opens the modal with the selected offer's details.

#### src/components/OffersList/OffersList.tsx
The OffersList component has been updated to include a click handler on each list item that opens the modal with the selected offer's details.

#### src/context/DataContext.tsx and src/context/ModalContext.tsx
The modal related state and functions have been moved from DataContext to a new ModalContext. This is a good practice as it separates concerns and makes the code more maintainable.

#### src/main.tsx
The ModalProvider has been added to the component tree in the main file. This allows all child components to access the modal related state and functions.

#### src/utils/index.ts
A utility function `countDaysAgo` has been added. This function calculates the number of days between the current date and the provided date. This function is used in the OfferDetailsModal component to display when the job offer was added.

#### Other files
Other changes in files like `package.json`, `tsconfig.json`, and various component files are minor and mostly related to code cleanup, refactoring, and styling changes.

### Suggestions
No major issues have been found in the code changes. The code is clean, well-organized, and follows good practices. The changes are in line with the task requirements. Therefore, no specific suggestions for improvements are provided.

2023-11-03 19:21 UTC, merged